#!/bin/sh

set -o errexit
set -o pipefail

if [ ! -d /kubelet-plugins/spangenberg.io~xenserver ]; then
  mkdir /kubelet-plugins/spangenberg.io~xenserver
fi

cp /usr/local/bin/xenserver /kubelet-plugins/spangenberg.io~xenserver/.tmp_xenserver
mv -f /kubelet-plugins/spangenberg.io~xenserver/.tmp_xenserver /kubelet-plugins/spangenberg.io~xenserver/xenserver

while : ; do
  sleep 3600
done
